export const INITIATE_STATES = 'INITIATE_STATES'
export const SHOW_MODAL_TRUE = 'SHOW_MODAL_TRUE'
// export const INITIATE_STATES = 'INITIATE_STATES'
// export const INITIATE_STATES = 'INITIATE_STATES'